config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :api do
    namespace :v1 do
      post "/ogcreateorder", to: "orders#ogcreateorder", as: "ogcreateorder"
      resources :subscriptions do
        member do
          patch :pause
          patch :unpause
          get :cancellation
          patch :cancel
        end
      end
    end
  end

  namespace :admin do
    resources :subscription_frequencies
    resources :subscriptions, except: [:new, :destroy, :show] do
      member do
        patch :sendnow
        patch :pause
        patch :unpause
        get :cancellation
        patch :cancel
        patch :uncancel
        get :comments
        get "new_cc", to: "subscriptions#new_cc"
        post "new_cc_update", to: "subscriptions#new_cc_update"
      end

    end
    get "subscriptionsreport", to: "subscriptions#subscriptionsreport"
    get "order_placing", to: "subscriptions#order_placing"
  end

  resources :subscriptions, except: [:new, :destroy, :show] do
    member do
      patch :sendnow
      patch :pause
      patch :unpause
      get :cancel
      patch :cancel
      patch :uncancel
      get "new_cc", to: "subscriptions#new_cc"
      post "new_cc_update", to: "subscriptions#new_cc_update"
    end
  end

end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do

  has_many :subscriptions, through: :variants_including_master, source: :subscriptions, dependent: :restrict_with_error
  has_many :product_subscription_frequencies, class_name: "Spree::ProductSubscriptionFrequency", dependent: :destroy
  has_many :subscription_frequencies, through: :product_subscription_frequencies, dependent: :destroy

  alias_attribute :subscribable, :is_subscribable

  self.whitelisted_ransackable_attributes += %w( is_subscribable )

  scope :subscribable, -> { where(subscribable: true) }

  #validates :subscription_frequencies, presence: true, if: :subscribable?

end

app/views/spree/admin/products/_subscribable.html.erb
<div data-hook="admin_product_form_subscribable">
  <%= f.field_container :subscribable, class: ['form-group'] do %>
    <%= f.check_box :subscribable, class: 'form-control', class: "subscribable-option subscribable_checkbox" %>
    <%= f.label :subscribable, Spree.t(:subscribable), class: "subscribable_label" %>
    <%= f.error_message_on :subscribable %>
  <% end %>
</div>
<div id="subscribable_options" class=<%= @product.subscribable? ? '' : 'hidden' %>>
  <%= f.collection_check_boxes :subscription_frequency_ids, Spree::SubscriptionFrequency.all, :id, :title, { include_hidden: false } do |builder| %>
    <%= builder.label { builder.check_box(class: "subscribable-option") + builder.text } %>
    <br>
  <% end %>
</div>

app/views/spree/admin/products/_subscribable_filter.html.erb
<div class='field checkbox'>
  <label>
    <%= f.check_box :is_subscribable_eq, { :checked => params[:q][:is_subscribable_eq] == '1' }, '1', nil %>
    <%= Spree.t(:show_subscribable ) %>
  </label>
</div>

app/views/spree/admin/products/_subscribable_listing_content.html.erb
<td class="text-center"><%= product.subscribable? ? "Yes" : "No" %></td>

app/views/spree/admin/products/_subscribable_listing_header.html.erb
<th class="text-center"><%= Spree.t(:subscribable) %></th>