config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :api do
    namespace :v1 do
      post "/ogcreateorder", to: "orders#ogcreateorder", as: "ogcreateorder"
      resources :subscriptions do
        member do
          patch :pause
          patch :unpause
          get :cancellation
          patch :cancel
        end
      end
    end
  end

  namespace :admin do
    resources :subscription_frequencies
    resources :subscriptions, except: [:new, :destroy, :show] do
      member do
        patch :sendnow
        patch :pause
        patch :unpause
        get :cancellation
        patch :cancel
        patch :uncancel
        get :comments
        get "new_cc", to: "subscriptions#new_cc"
        post "new_cc_update", to: "subscriptions#new_cc_update"
      end

    end
    get "subscriptionsreport", to: "subscriptions#subscriptionsreport"
    get "order_placing", to: "subscriptions#order_placing"
  end

  resources :subscriptions, except: [:new, :destroy, :show] do
    member do
      patch :sendnow
      patch :pause
      patch :unpause
      get :cancel
      patch :cancel
      patch :uncancel
      get "new_cc", to: "subscriptions#new_cc"
      post "new_cc_update", to: "subscriptions#new_cc_update"
    end
  end

end

app/models/spree/line_item_decorator.rb
Spree::LineItem.class_eval do

  attr_accessor :subscription_frequency_id

  #after_create :create_subscription!, if: :subscribable?
  #after_update :update_subscription_quantity, if: :can_update_subscription_quantity?
  #after_update :update_subscription_attributes, if: :can_update_subscription_attributes?
  after_destroy :destroy_associated_subscription!, if: :subscription?

  def subscription_attributes_present?
    subscription_frequency_id.present?
  end

  def updatable_subscription_attributes
    {
      subscription_frequency_id: frequency || subscription.subscription_frequency_id,
    }
  end

  def subscribable?
    auto_delivery && frequency.present?
  end

  def subscription?
    !!subscription
  end

  def subscription
    order.subscriptions.find_by(variant: variant)
  end

  def create_subscription!
    subscription= order.subscriptions.create! subscription_attributes
    subscription.update(
        source: order.payments.completed.from_credit_card.last.source,
        enabled: true,
        ship_address: order.ship_address.clone,
        bill_address: order.bill_address.clone
    )
  end
  
  private



    def subscription_attributes
      #ad_adjust=adjustments.eligible.where(label:"Promotion (Auto Delivery)").last["amount"] / quantity
      {
        subscription_frequency_id: frequency,
        #price: price + ad_adjust,
        variant: variant,
        quantity: quantity,
        user_id: order.user_id
      }
    end

    def update_subscription_quantity
      subscription.update(quantity: quantity)
    end

    def update_subscription_attributes
      subscription.update(updatable_subscription_attributes)
    end

    def destroy_associated_subscription!
      subscription.destroy!
    end

    def can_update_subscription_attributes?
      subscription? && subscription_attributes_present?
    end

    def can_update_subscription_quantity?
      subscription? && quantity_changed?
    end

end

app/models/spree/order_subscription.rb
module Spree
  class OrderSubscription < Spree::Base

    self.table_name = "spree_orders_subscriptions"

    belongs_to :order, class_name: "Spree::Order"
    belongs_to :subscription, class_name: "Spree::Subscription"

    validates :order, :subscription, presence: true
    validates :order_id, uniqueness: { scope: :subscription_id, allow_blank: true }

  end
end

app/models/spree/ordergroove_configuration.rb
module Spree
  class OrdergrooveConfiguration

    def self.account
      bronto_yml=File.join(Rails.root,'config/ordergroove.yml')
      if File.exist? bronto_yml
        bronto_yml=File.join(Rails.root,'config/ordergroove.yml')
        YAML.load(File.read(bronto_yml))
      end
    end
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do

  has_many :subscriptions, through: :variants_including_master, source: :subscriptions, dependent: :restrict_with_error
  has_many :product_subscription_frequencies, class_name: "Spree::ProductSubscriptionFrequency", dependent: :destroy
  has_many :subscription_frequencies, through: :product_subscription_frequencies, dependent: :destroy

  alias_attribute :subscribable, :is_subscribable

  self.whitelisted_ransackable_attributes += %w( is_subscribable )

  scope :subscribable, -> { where(subscribable: true) }

  #validates :subscription_frequencies, presence: true, if: :subscribable?

end

app/controllers/spree/admin/payments_controller_decorator.rb
Spree::Admin::PaymentsController.class_eval do

  private

    def load_data
      @amount = params[:amount] || load_order.total
      @payment_methods = available_payment_methods
      @payment_method = @payment.try(:payment_method) || @payment_methods.first
    end

    def available_payment_methods
      @order.subscriptions.any? ? Spree::Gateway.available_on_back_end : Spree::PaymentMethod.available_on_back_end
    end

end

app/controllers/spree/admin/subscription_frequencies_controller.rb
module Spree
  module Admin
    class SubscriptionFrequenciesController < Spree::Admin::ResourceController
    end
  end
end

app/controllers/spree/admin/subscriptions_controller.rb
module Spree
  module Admin
    class SubscriptionsController < Spree::Admin::ResourceController

      before_action :ensure_not_cancelled, only: [:update, :cancel, :cancellation, :pause, :unpause]
      after_action :log_action, except: [:new_cc, :show, :index, :edit, :order_placing, :subscriptionsreport, :build_source, :comments]
      
      def order_placing
        params[:q] = {} unless params[:q]
        params[:q][:place_status_cont] =""
        if params[:q][:placed_at_gt].blank?
          params[:q][:placed_at_gt] = Time.zone.now.beginning_of_day
        else
          params[:q][:placed_at_gt] = Time.zone.parse(params[:q][:placed_at_gt]).beginning_of_day rescue Time.zone.now.beginning_of_day
        end

        if params[:q] && !params[:q][:placed_at_lt].blank?
          params[:q][:placed_at_lt] = Time.zone.parse(params[:q][:placed_at_lt]).end_of_day rescue Time.zone.now.end_of_day
        end

        @sd = Time.parse(params[:q][:placed_at_gt].to_s).beginning_of_day rescue Time.now.beginning_of_day
        @ed = Time.parse( params[:q][:placed_at_lt].to_s).end_of_day rescue @sd.end_of_day

        if @sd > @ed
          @sd, @ed = @ed.beginning_of_day, @sd.end_of_day
        end
        
        @days_in_report = (@ed+1).to_date - @sd.to_date

        time_range = @sd..@ed
        #byebug
        @search=Spree::Subscription.search(params[:q])
        #@subscriptions = @search.result.page(params[:page]).per(30)
        @subscriptions=Spree::Subscription.where(:placed_at =>time_range ).page(params[:page]).per(30)

        #@search=Spree::Order.joins("join spree_orders_subscriptions on spree_orders_subscriptions.order_id = spree_orders.id join spree_subscriptions on spree_subscriptions.id = spree_orders_subscriptions.subscription_id").search(params[:q])
        #@autodelivery_orders = @search.result


      end

      def subscriptionsreport
        params[:q] = {} unless params[:q]
        @search=Spree::Subscription.search(params[:q])
        if params[:q][:completed_at_gt].blank?
          params[:q][:completed_at_gt] = Time.zone.now - 30.days
        else
          params[:q][:completed_at_gt] = Time.zone.parse(params[:q][:completed_at_gt]).beginning_of_day rescue Time.zone.now - 30.days
        end

        if !params[:q][:completed_at_lt].blank?
          params[:q][:completed_at_lt] = Time.zone.parse(params[:q][:completed_at_lt]).end_of_day rescue Time.zone.now
        else
          params[:q][:completed_at_lt] = Time.zone.now
        end

        @sd = Time.parse(params[:q][:completed_at_gt].to_s).beginning_of_day rescue Time.now.beginning_of_day
        @ed = Time.parse( params[:q][:completed_at_lt].to_s).end_of_day rescue @sd.end_of_day

        if @sd > @ed
          @sd, @ed = @ed.beginning_of_day, @sd.end_of_day
        end

        @days_in_report = (@ed+1).to_date - @sd.to_date

        time_range = @sd..@ed
        day_range=@sd.to_date..@ed.to_date


        @reports=[['Day', 'New Subscriptions', 'New Orders', 'Auto Delivered Orders']]
        day_range.each do |date|
          one_day_range=date.beginning_of_day..date.end_of_day
          subscriptions=Spree::Subscription.select("date(created_at) as ordered_date, number as new_subscriptions").where('spree_subscriptions.created_at' => one_day_range).length
          orders=Spree::Order.select("date(completed_at) as ordered_date, number as new_orders").where('spree_orders.completed_at' => one_day_range).length

          auto_delivered_orders=Spree::Order.select("date(completed_at) as ordered_date, number as auto_delivered_orders").where('spree_orders.channel' => 'order_groove', 'spree_orders.completed_at' => one_day_range).length

          @reports << [date.to_s, subscriptions, orders, auto_delivered_orders]
        end
        

      end

      def edit
        @title="Subscription Edit"
      end

      def update
        if @subscription.update(subscription_attributes)
          flash[:success] = 'Subscription updated successfully'
          respond_to do |format|
            format.html { redirect_to edit_admin_subscription_path(@subscription), success: t('.success') }
            format.json { render json: { subscription: { price: @subscription.price, id: @subscription.id } }, status: 200 }
          end
        else
          respond_to do |format|
            format.html { edit_admin_subscription_path(@subscription) }
            format.json { render json: { errors: @subscription.errors.full_messages.to_sentence }, status: 422 }
          end
        end
      end

      def new_cc
         @credit_card=Spree::CreditCard.new
         render :credit_card
      end

      def new_cc_update
        #byebug
        payment_method=Spree::PaymentMethod.active.where("name like '%Credit Card%'").first
        source_attributes=params["subscription_source"].values
        source = payment_method.payment_source_class.new(params.require("subscription_source").permit(:name, :verification_value, :cc_type))
        source.expiry=params[:subscription_source]["expiry"]

        source.number= params[:subscription_source][:number]
        source.cc_type= source.try_type_from_number
        #@subscription.source.last_digits= nil
        source.payment_method_id = payment_method.id
        begin
          payment=Spree::Payment.create(:order_id=>@subscription.parent_order.id,
                                        :amount=>1.0,
                                        :payment_method_id=>payment_method.id
          )

          payment.source = source
          payment_method.create_profile(payment)  #authorize need profile before authorize
        res=payment_method.authorize(1, source, {})
        rescue e
          flash[:error] = e.to_s
          payment.destroy if payment
          redirect_to(new_cc_admin_subscription_path(@subscription)) && return
        end
        if res.success?
          #byebug      

          payment.source.save!

          if params["apply_to_all"]
            user= @subscription.user
            subscriptions=user.subscriptions
            subscriptions.each do |subscription|
              subscription.source= payment.source
              subscription.update_attributes(source: source, attempts:0)
            end
          else
            @subscription.source= payment.source
            @subscription.update_attributes(source: source, attempts:0)
          end

          payment.destroy
          
          flash[:success] = t('.success')
          redirect_to(edit_admin_subscription_path(@subscription)) && return
        else
          flash[:error] = t('.error')
          redirect_to(new_cc_admin_subscription_path(@subscription)) && return
        end
         #Rails.logger.info(params.inspect);
      end

      def build_source
        if source_attributes.present? && source.blank? && payment_method.try(:payment_source_class)
          self.source = payment_method.payment_source_class.new(source_attributes)
          source.payment_method_id = payment_method.id
        end
      end

      def cancellation
      end

      def cancel
        if @subscription.cancel_with_reason(cancel_subscription_attributes)
          redirect_to collection_url, success: t('.success')
        else
          render :cancellation
        end
      end

      def pause
        if @subscription.pause
          render json: {
            flash: t('.success'),
            url: unpause_subscription_path(@subscription),
            button_text: Spree::Subscription::ACTION_REPRESENTATIONS[:unpause],
            confirmation: Spree.t("subscriptions.confirm.activate")
          }, status: 200
        else
          render json: {
            flash: t('.error')
          }, status: 422
        end
      end

      def sendnow
        if @subscription.process
          order=@subscription.orders.last
          render json: {
              flash: t('.success'),
              url: edit_admin_order_path(order),
              button_text: order.number,
              to_link: true,
              next_occurrence_at: @subscription.next_occurrence_at.to_date,
              confirmation: Spree.t("subscriptions.confirm.sendnow")
          }, status: 200
        else
          render json: {
              flash: t('.error')
          }, status: 422
        end
      end

      def unpause
        if @subscription.unpause
          render json: {
            flash: t('.success', next_occurrence_at: @subscription.next_occurrence_at.to_date.to_formatted_s(:rfc822)),
            url: pause_subscription_path(@subscription),
            button_text: Spree::Subscription::ACTION_REPRESENTATIONS[:pause],
            next_occurrence_at: @subscription.next_occurrence_at.to_date,
            confirmation: Spree.t("subscriptions.confirm.pause")
          }, status: 200
        else
          render json: {
            flash: t('.error')
          }, status: 422
        end
      end

      private
      def log_action
        begin
          if action_name=="update"
            @subscription.comments.create(:title => "#{action_name} requested", :comment => "Sent #{action_name.upcase} to server with result:  #{sub_data}", :user => spree_current_user)
          elsif action_name=="new_cc_update"
            @subscription.comments.create(:title => "#{action_name} requested", :comment => "Sent #{action_name.upcase} to server with cc:  #{@subscription.source.last_digits}", :user => spree_current_user)
          else
            @subscription.comments.create(:title => "#{action_name} requested", :comment => "Sent #{action_name.upcase} to server", :user => spree_current_user)
          end
        rescue
          #should we do more here. should be no error raised for this log.
        end
      end

      def sub_data
        changes=""
        changes +=" frequency: "+ @subscription.subscription_frequency_id.to_s
        changes +=" quantity: "+ @subscription.quantity.to_s

app/controllers/spree/admin/users_controller_decorator.rb
Spree::Admin::UsersController.class_eval do

  before_action :load_subscriptions, only: :edit
  
  private

    def load_subscriptions
      @orders = @user.orders.complete.order(completed_at: :desc)
      @subscriptions = Spree::Subscription.active.order(created_at: :desc).with_parent_orders(@orders)
    end

end

app/controllers/spree/api/v1/line_items_controller_decorator.rb
Spree::Api::V1::LineItemsController.class_eval do
  self.line_item_options =[ :auto_delivery, :frequency]
end

app/controllers/spree/api/v1/shipments_controller_decorator.rb
Spree::Api::V1::ShipmentsController.class_eval do

  def add
    quantity = params[:quantity].to_i
    if params[:options]
      options = params[:options]
    end
    options ||= {}
    options[:shipment] = @shipment

    @shipment.order.contents.add(variant, quantity, options)
    respond_with(@shipment, default_template: :show)
  end

end

app/controllers/spree/api/v1/subscriptions_controller.rb
module Spree
  module Api
    module V1
      class SubscriptionsController < Spree::Api::BaseController
        before_action :find_subscription, except: [:index]

        def show
          respond_with(@subscription, default_template: :show)
        end

        def update
          byebug
          if @subscription.update_attributes(subscription_params)
            respond_with(@subscription, default_template: :show)
          else
            invalid_resource!(@subscription)
          end
        end

        private

        def subscription_params
          params.require(:subscription).permit([:quantity, :subscription_frequency_id, :prior_notification_days_gap,:next_occurrence_at,:paused, :enabled, :cancellation_reasons])
        end

        def address_params
          params.require(:address).permit(permitted_address_attributes)
        end

        def find_order
          @order = Spree::Order.find_by!(number: order_id)
        end

        def find_subscription
           @subscription = Spree::Subscription.joins("join spree_orders on spree_subscriptions.parent_order_id=spree_orders.id").where("spree_subscriptions.id=? and spree_orders.user_id=?", params[:id], current_spree_user.id.to_s)

        end
        def find_address
          if @order.bill_address_id == params[:id].to_i
            @order.bill_address
          elsif @order.ship_address_id == params[:id].to_i
            @order.ship_address
          else
            raise CanCan::AccessDenied
          end
        end
      end
    end
  end
end

app/views/spree/subscriptions/_item.html.erb
<% currency = Money.new(1000, @subscription.parent_order.currency).currency %>

<%
  d='10'
  product= @subscription.variant.product
  pc=Spree::PromotionCategory.find_by_name("auto delivery")
  pc.promotions.where(promotion_rules: product.promotion_rules)

  prs=product.promotion_rules.where(promotion_id:pc.promotions)

  if prs.length>0
    promotion = prs.first.promotion
    d= promotion.name.gsub(/[^[\d|\.]]/, '')
  end
%>
<div class="subscription_head">
<div class="col-md-3 col-xs-5">
  <h2 class="title"> <%= Spree.t(:quantity) %></h2>
  <div class="sub_content">
    <% if !@subscription.not_changeable?%>
  <button class="_qty_helper _qty-spin-minus" type="button"></button>
    <% end %>
          <%= number_field :subscription, :quantity, { min: 1,max:999, disabled: @subscription.not_changeable? , class: "form-control", onChange: "update_product_info(this,#{@subscription.variant_id},#{d})"} %>
    <% if !@subscription.not_changeable? %>
    <button class="_qty_helper  _qty-spin-plus" type="button"></button>
      <% else %>
      <br>
      <label>Subscription Cancelled</label>
     <% end %>
          <%= f.error_message_on :quantity %>
          <br>
          <% if !@subscription.not_changeable? %>
      <span>
        <%= link_to 'Cancel', cancel_subscription_path(@subscription), method: :patch, class: 'cancel btn-danger btn btn-xs', data: { confirm: Spree.t("subscriptions.confirm.cancel") } %>
      </span>
      <br>
    <span id="pause_links">
      <% if @subscription.paused? %>
  <%= link_to Spree.t(:activate), "javascript:void(0)", class: "btn ajax_handler btn-xs btn-success", data: { url: unpause_subscription_path(@subscription), method: "PATCH", confirmation: Spree.t("subscriptions.confirm.activate") } %>
<% else %>
  <%= link_to Spree.t(:pause), "javascript:void(0)", class: "btn ajax_handler btn-xs btn-warning", data: { url: pause_subscription_path(@subscription), method: "PATCH", confirmation: Spree.t("subscriptions.confirm.pause") } %>
<% end %>
    </span>
      <br> <br>
      <%= button_link_to("Send Now", "javascript:void(0)", class: 'btn ajax_handler btn-xs btn-warning', data: { method: "PATCH", url: sendnow_subscription_path(@subscription), confirmation: Spree.t("subscriptions.confirm.sendnow") }, title: "Send it Now")%>

  <% end %>
</div>
</div>

      <div class="col-md-5 col-xs-7">
        <h2 class="title">Subscription Item</h2>
        <div class="sub_content">

        <div class="left"><%= product_image(@subscription.variant) %></div>
         <div>
          <div class="item_title"><%= @subscription.variant.product.name %> </div>
           <p class="item_option">
          <%= @subscription.variant.options_text %>
           </p>
          <% @product= @subscription.variant.product%>
          
          <div class="left">
          <%= render :partial => 'spree/shared/powerreviews_product_snippet', :locals => { :product => @subscription.variant.product, :showwrite => false }%>
          </div>
          <br>
          <% if @subscription.variant.in_stock? %>
            <div class="in-stock">
              <%= Spree.t(:in_stock) %>
            </div>
          <% else %>
            <div class="out-of-stock">
              <%= Spree.t(:out_of_stock) %>
            </div>
          <% end %>
         </div>
        </div>
      </div>


 <div class="col-md-4 col-xs-12">
   <h2 class="title">Price</h2>
        <div class="sub_content">
        <%vol_price=@subscription.variant.volume_price(@subscription.quantity,nil,@subscription.parent_order.currency)%>
        <%
          if volume_array(@subscription.variant)[0] < @subscription.variant.price_in(@subscription.parent_order.currency).price
            saving=true
          else
            saving=false
          end
        %>
        <div class="left">Original Price:</div>
        <div class="right"><span id="single_bottle_original_<%= @subscription.variant_id %>" class="original_price <%= saving ? "discounted" : ""%>"><%= currency.symbol %><%= '%.2f' % (@subscription.variant.price_in(@subscription.parent_order.currency).price *  @subscription.quantity) %></span>
        </div>
        <div class="clear"></div>
        <div class="volume_price" style="display:<%=saving ? "block" : "none" %>;">
          <div class="left">Volume Discount:</div>
          <div class="right original_price" id="single_bottle_save_<%= @subscription.variant_id %>">-<%= currency.symbol %><%= '%.2f' %  ((@subscription.variant.price_in(@subscription.parent_order.currency).price - vol_price) * @subscription.quantity) %></div>
          <div class="clear"></div>
        </div>


              <div class="left">Auto Delivery:</div>
              <div class="right"><span class="delivery_price">-<%= Spree::Money.new(vol_price*d.to_i*@subscription.quantity/100, :currency => currency) %></span></div>

          <div class="clear"></div>


        <div class="left summary_label">You Pay:</div>
        <div class="right original_price price_summary">
          <label><%= '%.2f' % ((vol_price - d.to_i* vol_price/100) *  @subscription.quantity) %></label>
        </div>
   </div>
      </div>
</div>
<div class="clear"></div>
<hr class="divider"/>
      <div class="col-md-4 col-xs-6">
        <strong class="sub_content">Next Order Date</strong>
        <%= f.field_container :next_occurrence_at, class: ["form-group"] do %>
          <%= f.text_field :next_occurrence_at, class: "form-control datepicker subscription_next_occurrence_at", disabled: @subscription.not_changeable? || @subscription.paused?, value: @subscription.next_occurrence_at.to_date %>
          <%= f.error_message_on :next_occurrence_at %>
        <% end %>
      </div>

      <div class="col-md-4 col-xs-6">
        <strong class="sub_content">Delivery every</strong>
        <%= f.field_container :frequency, class: ["form-group"] do %>
          <%= f.collection_select :subscription_frequency_id, Spree::SubscriptionFrequency.all, :id, :title, {}, { class: "form-control", disabled: @subscription.not_changeable? } %>
          <%= f.error_message_on :frequency %>
        <% end %>

      </div>
        <div class="col-md-4 col-xs-6">
        <strong class="sub_content">Email Reminder</strong>

        <div data-hook="prior_notification_days_gap">
          <%= f.field_container :prior_notification_days_gap, class: ["form-group"] do %>
            <%= number_field :subscription, :prior_notification_days_gap, class: "form-control", disabled: @subscription.not_changeable? %>
            days in advance
            <%= f.error_message_on :prior_notification_days_gap %>
          <% end %>
        </div>
        </div>   

<div class="clear"></div>
<hr class="divider"/>

app/views/spree/subscriptions/_pause_links.html.erb
<% if @subscription.paused? %>
  <%= link_to Spree.t(:activate), "javascript:void(0)", class: "btn ajax_handler #{ btn_class } btn-success", data: { url: unpause_subscription_path(@subscription), method: "PATCH", confirmation: Spree.t("subscriptions.confirm.activate") } %>
<% else %>
  <%= link_to Spree.t(:pause), "javascript:void(0)", class: "btn #{ btn_class } ajax_handler btn-warning", data: { url: pause_subscription_path(@subscription), method: "PATCH", confirmation: Spree.t("subscriptions.confirm.pause") } %>
<% end %>

app/views/spree/subscriptions/_subscription.html.erb
<% @subscription = subscription %>
<% currency = Money.new(1000, @subscription.parent_order.currency).currency %>

<%
  d='10'
  product= @subscription.variant.product
  pc=Spree::PromotionCategory.find_by_name("auto delivery")
  pc.promotions.where(promotion_rules: product.promotion_rules)

  prs=product.promotion_rules.where(promotion_id:pc.promotions)

  if prs.length>0
    promotion = prs.first.promotion
    d= promotion.name.gsub(/[^[\d|\.]]/, '')
  end
%>
<div class="subscription_head">
  <div class="col-md-4 col-xs-5">
    <h2 class="title"><%= @subscription.number %></h2>
    <div class="sub_content">

      <div>Deliver <strong><%= @subscription.quantity%></strong> <%= (@subscription.variant.product.package_unit || "bottle").downcase %><%= @subscription.quantity>1 ? "s": ""%> every <strong><%= @subscription.frequency.title%></strong></div>
      <div>Next Order Date: <strong><%= @subscription.next_occurrence_at.to_date %></strong></div>
      
      <br>
      <% if subscription.cancelled? %>
        Subscription Cancelled
      <% else %>
        <lable>Last order placing status: </lable><%= subscription.place_status || 'NA'%>
        <br>
        <div class="subscription_buttons">
        <span id="pause_links"><%= render partial: 'spree/subscriptions/pause_links', locals: { btn_class: "btn-xs" } %></span>
        <%= link_to Spree.t(:edit), edit_subscription_path(subscription), class: "btn btn-xs btn-info" %>
        <%#= link_to Spree.t("subsriptions.admin.cancel"), "javascript:void(0)", class: "btn btn-xs btn-danger", data: { method: "PATCH", confirmation: Spree.t("subscriptions.confirm.cancel"), url: cancel_subscription_path(subscription) } %>
          <%= button_link_to Spree.t("subsriptions.admin.cancel"), cancel_subscription_path(@subscription), class: 'btn-danger btn-xs', icon: 'cancel', title: "Cancel" %>

        </div>
    <% end %>
    </div>
  </div>

  <div class="col-md-5 col-xs-7">
    <h2 class="title">Subscription Item</h2>
    <div class="sub_content">

      <div class="left"><%= product_image(@subscription.variant) %></div>
      <div>
        <div class="item_title"><%= @subscription.variant.product.name %> </div>
        <p class="item_option">
          <%= @subscription.variant.options_text %>
        </p>
        <% @product= @subscription.variant.product%>

        <div class="left">
          <%= render :partial => 'spree/shared/powerreviews_product_snippet', :locals => { :product => @subscription.variant.product, :showwrite => false }%>
        </div>
        <br>
        <% if @subscription.variant.in_stock? %>
          <div class="in-stock">
            <%= Spree.t(:in_stock) %>
          </div>
        <% else %>
          <div class="out-of-stock">
            <%= Spree.t(:out_of_stock) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>


  <div class="col-md-3 col-xs-12">
    <h2 class="title">Price</h2>
    <div class="sub_content">
      <%vol_price=@subscription.variant.volume_price(@subscription.quantity,nil,@subscription.parent_order.currency)%>

      <%
        if volume_array(@subscription.variant)[0] < @subscription.variant.price_in(@subscription.parent_order.currency).price
          saving=true
        else
          saving=false
        end
      %>
      <div class="left">Original Price:</div>
      <div class="right"><span id="single_bottle_original_<%= @subscription.variant_id %>" class="original_price <%= saving ? "discounted" : ""%>"><%= currency.symbol %><%= '%.2f' % (@subscription.variant.price_in(@subscription.parent_order.currency).price *  @subscription.quantity) %></span>
      </div>
      <div class="clear"></div>
      <div class="volume_price" style="display:<%=saving ? "block" : "none" %>;">
        <div class="left">Volume Discount:</div>
        <div class="right original_price" id="single_bottle_save_<%= @subscription.variant_id %>">-<%= currency.symbol %><%= '%.2f' %  ((@subscription.variant.price_in(@subscription.parent_order.currency).price - vol_price) * @subscription.quantity) %></div>
        <div class="clear"></div>
      </div>


      <div class="left">Auto Delivery:</div>
      <div class="right"><span class="delivery_price">-<%= Spree::Money.new(vol_price*d.to_i*@subscription.quantity/100, :currency => currency) %></span></div>

      <div class="clear"></div>


      <div class="left summary_label">You Pay:</div>
      <div class="right original_price price_summary">
        <label><%= '%.2f' % ((vol_price - d.to_i* vol_price/100) *  @subscription.quantity) %></label>
      </div>
    </div>
  </div>
</div>
<div class="clear"></div>
<hr class="divider"/>